---
id: 600b3da0-dfe5-4a0c-9cd0-2e86feedba84
registrations:
  - validity:
      - input:
          auxiliaryType: checkbox
          class: { id: 1938d89b-a935-412d-a23c-02709fe63c0c, name: System Access }
          name: Schultz Fasit
          category: system-access
          system: { id: 3ee8cbd2-70a9-40be-8d31-0a1242b3f308, name: Hjertekøbing Fasit }
        from: 2005-01-01T00:00:00.000Z
...
